steps:
  - name: 'cnservices/python-virtualenv'
    args: ['make', 'lint']

  - name: 'cnservices/python-virtualenv'
    args: ['make', 'test']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_CONTAINER_HOSTNAME}/$PROJECT_ID/${_SERVICE_NAME}', '.']

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_CONTAINER_HOSTNAME}/$PROJECT_ID/${_SERVICE_NAME}"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "${_CONTAINER_HOSTNAME}/$PROJECT_ID/${_SERVICE_NAME}",
        "--update-env-vars",
        "TRANSACTION_NAMESPACE=${_TRANSACTION_NAMESPACE},BALANCE_TOPIC_ID=${_BALANCE_TOPIC_ID},ACCOUNTS_SERVICE_URL=${_ACCOUNTS_SERVICE_URL}",
        "--region",
        "${_REGION}",
        "--allow-unauthenticated",
        "--platform",
        "managed",
      ]

  - id: "create pubsub subscription"
    name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/bash
    args:
      - -c
      - |
        transaction_url=$(gcloud run services describe ${_SERVICE_NAME} --platform=managed --region=europe-west1 | grep https://${_SERVICE_NAME})
        check_command=$(gcloud pubsub subscriptions list | grep "${transaction_url}")
        if [[ $check_command = '' ]]; then
          gcloud pubsub subscriptions create push_transactions_to_service --topic=transactions --push-endpoint=${transaction_url}/transactions
        else
          echo Subscription already exists
        fi

  - id: "create transactions collection index"
    name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/bash
    args:
      - -c
      - |
        index_ref=$(gcloud alpha firestore indexes composite list | grep transactions)
        if [[ $index_ref = '' ]]; then
          gcloud alpha firestore indexes composite create \
          --collection-group=${_TRANSACTION_NAMESPACE} \
          --field-config field-path=account_number,order=ascending \
          --field-config field-path=timestamp,order=descending
        else
          echo Composite Index already exists
        fi
        
substitutions:
  _CONTAINER_HOSTNAME: eu.gcr.io
  _SERVICE_NAME: gcp-training-transaction-service
  _REGION: europe-west1
  _TRANSACTION_NAMESPACE: transactions
  _BALANCE_TOPIC_ID: balance
  _ACCOUNTS_SERVICE_URL: http://localhost:5001
